### ISSUE TITLE
Add "Selectiveness" option to show level on battle pets

### ISSUE THREAD

**Issue by tflo** [kemayo/wow-simpleitemlevel#21]
Now that we have a working level indicator for battle pets (thanks again!), it would be great if we could activate this _without activating all the irrelevant items._ (It isn't really that interesting that an Attendant's Pocket Portal is level 50 ;)

Something like:

```text
Selectiveness
   
   Show also on battle pets [✓]
   Show also on other items [ ]
```

Thanks for considering,

– Tom

**Comment by kemayo** [comment]
I went a bit further 
![image](https://user-images.githubusercontent.com/2187/208227019-30a56323-c5d9-4228-b407-ca6b6a034359.png)

**Comment by tflo** [comment]
This is great. I almost wanted to propose to make equippable items (in bags) optional too, so that we can display SimpleItemLevel for the equipment slots and for pets in bags only, i.e., not conflicting with a bag addon that already displays equipment item levels in bags.

**Comment by kemayo** [comment]
I think going any further than this is mostly tricky because it requires making an okay config UI for it. The next step past here is something multifaceted, where for every place it shows it lets you override all the other config choices. Which is totally doable, but I worry about it being confusing.
